name: Lint and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and test server
        working-directory: ./server
        run: |
          npm install
          npm run format
          npm test

      - name: Install and format client
        working-directory: ./client
        run: |
          npm install
          npm run format
