name: Audit Node.js Dependencies

on:
  push:
    paths:
      - '**/package.json'
      - '**/package-lock.json'
  schedule:
    - cron: '0 0 * * 1' # Weekly on Monday

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Audit server dependencies
        working-directory: ./server
        run: |
          npm install
          npm audit --audit-level=moderate

      - name: Audit client dependencies
        working-directory: ./client
        run: |
          npm install
          npm audit --audit-level=moderate
